### ISSUE TITLE
Suggest to make it installable

### ISSUE THREAD

**Issue by kernie66** [LeonidGoldberg/pushcut-python#1]
Hi,

I like Pushcut and found your library when I though of writing my own. But yours is so nice that I use it instead.

But I would like to install it from GitHub with 'pip'. All I think is missing is the 'setup.py', see the second answer [here](https://stackoverflow.com/questions/1471994/what-is-setup-py). Would you consider adding it, to make it easier to install and use?

Regards,
Kenneth

**Comment by goleos** [comment]
Hi,

Thank you for your feedback and I'm glad that you found my library useful. I have added the 'setup.py' file now so the package should be installable.

Best wishes,
Leonid
